live_config_reload = false
working_directory = "None"
[mouse]
hide_when_typing = true
[env]
TERM = "xterm-256color"
[window]
opacity = 1
decorations_theme_variant = "Dark"
decorations = "Buttonless"
[cursor]
style = "Block"
[colors.primary]
background = "#181818"
foreground = "#f8f8f2"
[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
magenta = "#ff79c6"
cyan = "#ffffa7"
blue = "#faee00"
white = "#f8f8f2"
# [colors.cursor]
# cursor = "0x000000"
# text = "0xffffff"
[font]
size = 14.0
[font.offset]
x = 0
y = 0
[font.normal]
family = "Iosevka"
style = "Medium"
[font.bold]
family = "Iosevka"
style = "Medium"
[font.italic]
family = "Iosevka"
style = "Light Italic"
